<?php

namespace lpdw\SearchEngineBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function lastCat()
    {
        $qb = $this->createQueryBuilder('p');
        $qb->setMaxResults(5)
           ->orderBy('p.id', 'DESC');
        return $qb->getQuery()
                  ->getResult();
    }
}
