<?php

namespace lpdw\SearchEngineBundle\Repository;

/**
 * FeatureValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeatureValueRepository extends \Doctrine\ORM\EntityRepository
{


    public function findByFeatureCVandElement($featureCV, $element){

        $result = $this->createQueryBuilder('f')
            ->where('f.element=:element')
            ->AndWhere('f.featureCV IN (:featureCV)')
            ->setParameter("element", $element)
            ->setParameter("featureCV", $featureCV)
            ->getQuery()
            ->getResult();

        return $result;
    }
    public function findOneByFeatureCVandElement($featureCV, $element){

        $result = $this->createQueryBuilder('f')
            ->where('f.element=:element')
            ->AndWhere('f.featureCV IN (:featureCV)')
            ->setParameter("element", $element)
            ->setParameter("featureCV", $featureCV)
            ->getQuery()
            ->getSingleResult();

        return $result;
    }

}
