<?php

namespace lpdw\SearchEngineBundle\Repository;

/**
 * FeatureCategoryValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeatureCategoryValueRepository extends \Doctrine\ORM\EntityRepository
{
}
